
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LuxuryWatches.Data
{

using System;
    using System.Collections.Generic;
    
public partial class khachHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public khachHang()
    {

        this.donHangs = new HashSet<donHang>();

    }


    public string tkThanhVien { get; set; }

    public string eMail { get; set; }

    public string soDT { get; set; }

    public string matKhau { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<donHang> donHangs { get; set; }

}

}
